(define-module (oc configurations fonts-conf)
  #:export (%custom-fonts-packages
            %custom-fonts-configuration))

(define %custom-fonts-packages
  (list
      "font-iosevka"
      "font-sarasa-gothic"
      "font-google-noto"
      "font-google-noto-emoji"
      "font-google-noto-sans-cjk"
      "font-google-noto-serif-cjk"
      ))

(define %custom-fonts-configuration
  '("~/.guix-home/profile/share/fonts"
    (match (@ (target font)) 
           (edit (@ (name antialias) (mode assign)) 
                 (bool true) 
                 ) 
           (edit (@ (name embeddedbitmap) (mode assign)) 
                 (bool false) 
                 ) 
           (edit (@ (name hinting) (mode assign)) 
                 (bool true) 
                 ) 
           (edit (@ (name hintstyle) (mode assign)) 
                 (const hintnone) 
                 ) 
           (edit (@ (name lcdfilter) (mode assign)) 
                 (const lcddefault) 
                 ) 
           (edit (@ (name rgba) (mode assign)) 
                 (const rgb) 
                 ) 
           ) 

    (match (@ (target font)) 
           (test (@ (name family) (compare contains)) 
                 (string Emoji) 
                 ) 
           (edit (@ (name hinting) (mode assign)) 
                 (bool true) 
                 ) 
           (edit (@ (name hintstyle) (mode assign)) 
                 (const hintslight) 
                 ) 
           (edit (@ (name embeddedbitmap) (mode assign)) 
                 (bool true) 
                 ) 
           ) 

    (alias (@ (binding strong)) 
           (family serif) 
           (prefer 
             (family Noto Serif) 
             ) 
           ) 


    (alias (@ (binding strong)) 
           (family sans-serif) 
           (prefer 
             (family Noto Sans) 
             ) 
           ) 


    (alias (@ (binding strong)) 
           (family monospace) 
           (prefer 
             (family Iosevka) 
             ) 
           ) 


    (alias (@ (binding strong)) 
           (family system-ui) 
           (prefer 
             (family Noto Sans) 
             ) 
           ) 





    (match (@ (target pattern)) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ja) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK JP) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ko) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK KR) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hans) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK TC) 
                 ) 
           ) 


    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-cn) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-tw) 
                 ) 
           (test (@ (name family)) 
                 (string serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Serif CJK TC) 
                 ) 
           ) 





    (match (@ (target pattern)) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Ubuntu) 
                 (family Noto Sans) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ja) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK JP) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ko) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK KR) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hans) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant-hk) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK HK) 
                 ) 
           ) 


    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-cn) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-tw) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hk) 
                 ) 
           (test (@ (name family)) 
                 (string sans-serif) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK HK) 
                 ) 
           ) 





    (match (@ (target pattern)) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Iosevka Term) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ja) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term J) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ko) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term K) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hans) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant-hk) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term HC) 
                 ) 
           ) 


    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-cn) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-tw) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hk) 
                 ) 
           (test (@ (name family)) 
                 (string monospace) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Sarasa Term HC) 
                 ) 
           ) 





    (match (@ (target pattern)) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Ubuntu) 
                 (family Noto Sans) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ja) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK JP) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string ko) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK KR) 
                 ) 
           ) 



    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hans) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hant-hk) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK HK) 
                 ) 
           ) 


    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-cn) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK SC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-tw) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK TC) 
                 ) 
           ) 

    (match (@ (target pattern)) 
           (test (@ (name lang) (compare contains)) 
                 (string zh-hk) 
                 ) 
           (test (@ (name family)) 
                 (string system-ui) 
                 ) 
           (edit (@ (name family) (mode append) (binding strong)) 
                 (string Noto Sans CJK HK) 
                 ) 
           ) 
    ))
