complete -c systemd-boot-friend -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "init" -d 'Initialize systemd-boot-friend'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "list" -d 'List all available kernels'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "install" -d 'Install the kernel specified'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "list-installed" -d 'List all installed kernels'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "remove" -d 'Remove the kernel specified'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "update" -d 'Install all kernels and update boot entries'
complete -c systemd-boot-friend -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from init" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install" -r
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install" -s f -l force -d 'force overwrite the entry config or not'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from install" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list-installed" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from list-installed" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from remove" -r
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from update" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from update" -s V -l version -d 'Print version information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c systemd-boot-friend -n "__fish_seen_subcommand_from help" -s V -l version -d 'Print version information'
