[theme]
name = "nord-dark"
[theme.overrides]
idle_bg = "#3B4252"

[icons]
name = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
format = "{icon} 剩落 {percentage}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
icons_format = " {icon}"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
icons_format = " {icon}"
interval = 1

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "net"
device = "eno1"
format = "{speed_up;K}"
format_alt = "{speed_down;K}"
interval = 1

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", api_key = "fc2b2fbb28241d49e8a1adb3a228ddb4", city_id = "1808926", units = "metric", lang = "zh_tw" }

[[block]]
block = "sound"

[[block]]
block = "music"
player = "mpd"
buttons = ["prev", "play", "next"]

[[block]]
block = "time"
interval = 5
format = "禮拜%a %d/%m %R"
locale = "zh_TW"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

