[theme]
theme = "gruvbox-dark"
#[theme.overrides]
#idle_bg = "#3B4252"

[icons]
icons = "awesome5"

[[block]]
block = "focused_window"
format = " $title.str(max_w:20,rot_interval:0.5) |"
[block.theme_overrides]
#idle_bg = "#5e81ac"
#idle_fg = "#2e3440"
idle_bg = "#d79921"
idle_fg = "#3c3836"

[[block]]
block = "music"
player = ["Feishin", "mpd"]
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $prev $play $next |}"
#buttons = ["prev", "play", "next"]

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#format = "{icon} {percentage}"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{mem_used_percents}"
#format_swap = "{swap_used_percents}"

#[[block]]
#block = "cpu"
#interval = 1

[[block]]
block = "load"
interval = 1

#[[block]]
#block = "net"
#device = "eno1"
#format = "{speed_down;K}"
#format_alt = "{speed_up;K}"
#interval = 1
#
#[[block]]
#block = "net"
#device = "wlan0"
#format = "{speed_down;K}"
#format_alt = "{speed_up;K}"
#interval = 1

[[block]]
block = "weather"
service = { name = "openweathermap", api_key = "fc2b2fbb28241d49e8a1adb3a228ddb4", city_id = "5809844", units = "metric", lang = "zh_tw" }

#[[block]]
#block = "custom"
#command = ''' TOKEN=68f882283f289a177b71f764aa3aaf02a37eb2c2 SIMPLE=true aqicn Seattle '''

#[[block]]
#block = "backlight"

[[block]]
block = "sound"
max_vol = 100
#driver = "alsa"
#natural_mapping = true
#device = "hw:2"
#name = "HIFI DSD"

[[block]]
block = "time"
interval = 5
#format = " $icon $timestamp.datetime(f:'禮拜%a %m/%d %R', l:zh_TW) "
format = " $icon $timestamp.datetime(f:'%R') "

[[block]]
block = "battery"
device = "BAT0"

[[block]]
block = "custom"
command = ""
format = " "
interval = "once"
